name: Citation file info
description: Post the preferred citation file code
inputs:
  citation_file_path:
    description: The path to the citation.cff file
    required: true
  reviews_repo:
    description: The repository containing the review issue for the paper
    required: true
  issue_id:
    description: The issue number of the submission (to post a link to the tweet)
    required: true
  gh_token:
    description: The github token to use for replying to the review issue
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.1
        bundler-cache: true
        cache-version: citation-file
        bundler: Gemfile.lock
        working-directory: ${{ github.action_path }}
    - name: Comment with the citation file code
      shell: bash
      env:
        CITATION_FILE_PATH: ${{ inputs.citation_file_path }}
        ISSUE_ID: ${{ inputs.issue_id }}
        GITHUB_TOKEN: ${{ inputs.gh_token }}
        GH_REPO: ${{ inputs.reviews_repo }}
      run: |
        bundle exec ruby ${{ github.action_path }}/citation_info.rb
branding:
  icon: message-circle
  color: blue
